[package]
name = "snapshot"
version = "0.0.1"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]

[dependencies]
serde = ">=1.0.27"
serde_derive = ">=1.0.27"
serde_cbor = "0.11.1"
utils = { path="../utils" }
